### ISSUE TITLE
Align InputDialog form field type names with Flowable process variable type names

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-bpm-public#11]
Process variables names in flowable engine and input dialog form field types have slightly different names

For example, there is "entity-list" variable type and "entityList" form field type, "file-description" variable type and "file" form field type.

Although, these differences don't affect the runtime, it's worth  aligning form field type names with process variable type names. So for form fields type names should be "entity-list", "file-description", etc.

By form field type I mean the value that is written to the BPMN XML (`type` attribute of the `<jmix:formField> tag):
```xml
<jmix:formField id="myList" caption="My list" type="entityList" editable="true" required="false">
   <jmix:formFieldProperty name="uiComponent" value="entityPicker" />
    <jmix:formFieldProperty name="entityName" value="bs_User" />
</jmix:formField>
```

**Comment by maistrenkoIulia** [comment]
verified
