### ISSUE TITLE
Enum class resets during import the process in moeler

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-bpm-public#23]
[enum.txt](https://github.com/Haulmont/jmix-bpm-public/files/6629726/enum.txt)

Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2989-203
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC: 
run the app with BPM
Modeler> create new process>select start event>add process variable
set type = platform enum
enum class = io.jmix.bpmui.model.FormParamValueSource
Save process
close Modeler>open Modeler again>import saved previously process>viel emun variable
ER: Enum class should have value io.jmix.bpmui.model.FormParamValueSource
AR: Enum class is empty

![image](https://user-images.githubusercontent.com/66992566/121491771-5247d600-c9e7-11eb-8124-4eeb22461853.png)

*note*
the same problem for process variablу with type Entity / Entity List

**Comment by maistrenkoIulia** [comment]
Reproduced on 
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3119-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)
 TC: fot start task set form type = no form
create process variable with type enum>save draft>open again in modeler
![image](https://user-images.githubusercontent.com/66992566/122917469-1e699a80-d36f-11eb-91d9-39ca13053040.png)

**Comment by gorbunkov** [comment]
The separate issue exists for the last comment: #31

**Comment by gorbunkov** [comment]
If everything is file with Input dialog parameter editor, then @maistrenkoIulia please close the issue

**Comment by maistrenkoIulia** [comment]
1.1 - ok

**Comment by maistrenkoIulia** [comment]
1.0 - ok
