### ISSUE TITLE
Process element to work with data

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-bpm-public#27]
Implement process element to work with data.
According to spec.

**Comment by artemy63** [comment]
28.06.2021 - 50% done

**Comment by maistrenkoIulia** [comment]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3478-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)
TC: create 'Create entity' task with user entity and 'newUser' result var
create 'Modify entity' task
ER: 'newUser should be appeared in process var dropdown list
AR: no 'newUser' var
![image](https://user-images.githubusercontent.com/66992566/132216869-da5a426e-703b-4381-b801-ac52dddad70d.png)

![image](https://user-images.githubusercontent.com/66992566/132216825-59444b58-2bf3-4cc0-911c-23bc4e79ca7a.png)

**Comment by maistrenkoIulia** [comment]
for QA: Need to create TCs for regress

**Comment by artemy63** [comment]
Note: high-level description of functionality which should be provided - https://docs.google.com/document/d/1dykndkljn9aeTvLaFrXYCbX-Ai9J1RW5kqLigVnu6GY/edit#heading=h.5jadw0jwopuo

**Comment by gorbunkov** [comment]
@artemy63 We decided to hide the "Spring bean" value type in the Entity attribute editor behind the feature-toggle (some application property). 
By default, the "Spring bean" value type should not be visible in the Entity attribute editor for "Create entity" and "Modify entity" task types:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/7888486/134167804-2744424a-3f23-41e9-8f20-fa009eead2e6.png">

**Comment by artemy63** [comment]
Implementation notes

- Supported three types of entity tasks 
- - load entity by Jpql query and store it in some process variable
- - create entity with desired entity class and store it in some process variable
- - modify entity which stored in some process variable
- load entity task can operate with any Jpql query so return type is not known, more over result can contain more than one element, so operator can specify what he wants - operate with collection or take just one first result ("Save result as" comboBox).
-  in case of creating entity operator should specify desired entity type, after that all none-system attributes of such entity type can be specified, as value supported simple values and expressions.
- modify entity task assumes that operator selects existing process variable from list of available process variables. After that entity type will be detected automatically and all none-system attributes of this entity type can be filled with simple values or expressions. It is possible to specify process variable name directly by typing it name (actual when load entity task returns some entity), after that it is necessary to exactly specify entity type and proceed as usually with specifying entity attributes.

**Comment by artemy63** [comment]
It is necessary to check feature toggle oshowing spring bean constructor as possible entity attribute type, by default it is disabled but can be switched on with property "dataTaskSpringBeanEntityAttributeEnabled"
