### ISSUE TITLE
Enum class attribute of the start event process variable is erased in the process modeler

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-bpm-public#31]
1. Create new BPMN process using the modeler
2. Select the start event
3. Add new process variable using the properties panel
4. Type any process variable name and select the "Platform enum" type
5. Select any enum class from the dropdown list
<img width="506" alt="image" src="https://user-images.githubusercontent.com/7888486/122528077-002d3300-d02d-11eb-9ce9-7799c842d639.png">

6. Commit the process variable instance editor
7. Unselect the start event element
8. Select it again
9. Open the process variable created on previous steps

ER: Enum class combo-box has a value
AR: Enum class combo-box is empty
<img width="505" alt="image" src="https://user-images.githubusercontent.com/7888486/122528313-3965a300-d02d-11eb-959a-c3041d16a95e.png">

**Comment by artemy63** [comment]
Duplicated by Haulmont/jmix-bpm-public#23

**Comment by gorbunkov** [comment]
It is not a duplicate. It is about another screen - process variable editor, not input dialog parameter editor.
