### ISSUE TITLE
CallActiviti java.lang.IllegalArgumentException in "In-out variable mapping editor" (port to 1.0)

### ISSUE THREAD

**Issue by Desire456** [Haulmont/jmix-bpm-public#43]
See https://github.com/Haulmont/jmix-bpm-public/issues/41

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.0.0
Jmix Studio plugin version: 1.0.1-212
IntelliJ version: IntelliJ IDEA 2021.2
