### ISSUE TITLE
Process variable combobox of Multi-instance panel is empty

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-bpm-public#46]
1. Create new model
2. For the Start event mode select the "Input dialog" form type
3. Add input dialog parameter: process variable name is "approvers", type is "Entity list", entity name "User"
4. Add user task to the model
5. Set multi-instance type of the user task to "Parallel"
6. Select the "Process variable" value in the muti-instance collection source lookup

ER:
The "Process variable" combo-box contains the "approvers" variable

AR:
The "Process variable" combo-box is empty

Also we need to check that if process variables are defined for the start event node (instead of input dialog form) then process variables with users collection are displayed in the Multi-instance section of the user task

Forum topic: The "Process variable" combo-box contains the "approvers" variable

![Screenshot 2021-08-23 at 14 50 25](https://user-images.githubusercontent.com/7888486/130435573-b3c0b9d2-016d-422e-8482-67d09a8041f7.png)

![Screenshot 2021-08-23 at 14 51 16](https://user-images.githubusercontent.com/7888486/130435582-d297d00b-da9b-4860-8aba-cc8863fd822c.png)

**Comment by maistrenkoIulia** [comment]
verified
