### ISSUE TITLE
I got an error after opening the process definition edit screen 

### ISSUE THREAD

**Issue by a616101** [Haulmont/jmix-bpm-public#47]
I using dynamicBpmnService.injectUserTaskInProcessInstance method to update bpmModel, the ACT_RE_PROCDEF table will be like:
![image](https://user-images.githubusercontent.com/4496234/130716658-e0690afc-b8de-4e8b-9b18-d1e0f6beb7da.png)

ID a76081c4-0543-11ec-8fc4-acde48001122 and aa283f26-0541-11ec-8fc4-acde48001122 is derived from process:1:92f07d8a-0541-11ec-8fc4-acde48001122 

After update bpmModel, I got an error after opening the process definition edit screen 
![image](https://user-images.githubusercontent.com/4496234/130717151-86505cb0-45c6-4eb7-9e97-5a57a6c083f6.png)

I find ProcessDefinitionEdit 85 line:  use pdd -> pdd.getVersion().toString()，But a76081c4-0543-11ec-8fc4-acde48001122 and aa283f26-0541-11ec-8fc4-acde48001122  Version always equal 0.

Whether it can increase relevant judgments, Make it display normally

**Comment by gorbunkov** [comment]
It seems that we should add properties related to "derived" to the `ProcessDefinitionData` and fill these properties while building the `ProcessDefinitionData` from the `ProcessDefinition`. When versions lookup is initialized in the `ProcessDefinitionEdit` we should filter process definitions and exclude the ones that are derived from other processes.
