### ISSUE TITLE
"Condition -> Source" property for Flow element should be optional

### ISSUE THREAD

**Issue by konyashkina** [Haulmont/jmix-bpm-public#50]
After https://youtrack.jmix.io/issue/JST-1732  (please look video there).
It was fixed for Jmix Studio: in BPM Inspector user can leave this value empty. 
But there is no option to leave it empty in Modeler.

_Tested on_
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3492-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)

**Steps to reproduce:**

1. Run Jmix application and open Modeler to edit BPM process. 
2. Create 2 tasks and add a link (sequenceFlow element) between. 
3. Click the sequenceFlow element and go to Condition section. 
4. Set Source = Expression or User task outcome.
5. Try to change value in the Source field to leave it empty.
 
**Expected result:** 
User can set value in the  Source field and leave it empty after that. 

**Actual result:** 
There is no option to select empty value and leave sequenceFlow without condition details in Modeler. 

![condition-source](https://user-images.githubusercontent.com/85500330/132510437-7e93694f-c99d-4771-86cf-651ebf9d0aaf.png)

**Comment by gorbunkov** [comment]
I'm not sure we should do that.

1. As I see the "Expression" value in the "Condition source" combo-box is selected by default.
2. The "Condition source" value means nothing for the process engine, the only thing that really matters is the Condition expression or the user task outcome. Empty or filled condition source doesn't break anything
3. The same thing also happens with the User task "Assignee source" field. If we allow empty value for sequence flow we should also do that for the user task and probably for some other elements.

So my opinion is that this is not a bug, it doesn't break the system in any way and we should not do anything with it right now.
