### ISSUE TITLE
Support collection of data for email sending task

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-bpm-public#52]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3528-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)
TC:
crate process with load data task
(select e from l_User e where e.username <> 'admin')
with result var = out
save result as collection
create email task
AR:
the only way to send email to user is type ${out[0].emali}
Need to have ability to send email to all users from dataLoad result var

**Comment by gorbunkov** [comment]
Adding the multi-instance properties panel to the email task element should do the trick.

**Comment by maistrenkoIulia** [comment]
@artemy63  please, provide implementation description

**Comment by artemy63** [comment]
Now we support in To/Cc/Bcc field process variables which can return collection of strings each of them should represent a valid email address. In this case all these addresses will be used in appropriate addressee field.

**Comment by maistrenkoIulia** [comment]
verified
