### ISSUE TITLE
Text in WYSIWYG Email Content editor disappears after switching Content type  

### ISSUE THREAD

**Issue by konyashkina** [Haulmont/jmix-bpm-public#56]
(After testing _Email sending model element_ https://github.com/Haulmont/jmix-bpm-public/issues/6 )

BPM Send Email Task in Modeler: 
All typed text in WYSIWYG Email Content editor disappears after switching Content type  from HTML to Text and vise versa. 
It can be really annoying for users.

_Tested on_
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3528-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)

**Pre-conditions:** BPM and Email addons are installed. 

### **Case 1** 
**Steps to reproduce:**
1. Run Jmix application and open Modeler to edit BPM process.
2. Create 1 task with type = Send Email Task. 
3. Go to Details > Content type.  Click an icon on the right
![bpm-edit-icon](https://user-images.githubusercontent.com/85500330/134184221-a764b7fa-c943-40e6-8556-ae6daf4cc1fa.png)
 to start edit Content.  
4. ('Email Content edit' WYSIWYG window appears. Content type is HTML by default). Type some letters there. 
5. Change Content type to Text. 

**Expected result:** 
Content type is Text and the content already typed by user is shown as text below. 

**Actual result:**
Content type is Text, but all typed text disappears from this field.

### **Case 2** 
**Steps:**
1. Set Content type as Text in the 'Email Content edit' WYSIWYG window  and type some letters there. 
2.  Change Content type to HTML. 

**Expected result:** 
Content type is HTML and the content already typed by user is shown as text below. 

**Actual result:**
Content type is HTML, but all typed text disappears from this field.

**Comment by gorbunkov** [comment]
We will not implement the *HTML <-> Plain text* conversion, it's not an easy task and it's not worth doing it here. Instead we may add a confirmation dialog that says that the content will be cleared. The dialog will appear when the user changes the content-type

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3575-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Community Edition)

**Case 1.**
HTML -> Plain text conversion
A confirmation dialog appears and says that the content will be cleared:
![content-type-changed](https://user-images.githubusercontent.com/85500330/135851370-8eaee434-6034-48ba-8d50-07f954a51d6a.png)
 
**Case 2.**
Plain text  -> HTML conversion
Works fine.
