### ISSUE TITLE
Min size of properties panel should be defined

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-bpm-public#58]
Now it's possible to set size properties panel to unreadable
![image](https://user-images.githubusercontent.com/66992566/134498145-c455f1e7-ef01-47cf-a2e8-08b03431c8eb.png)

1. Need to define min size. Note, ability to hide the panel should not be affected
![image](https://user-images.githubusercontent.com/66992566/134498287-363cf86d-1d28-49d6-853e-4e64e9dc0ff6.png)

2. The count of shown strings in all tables of property panel should'n be less than 3

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4123-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
