### ISSUE TITLE
Fields table does not cleared after changing execution listener class implementation

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-bpm-public#61]
TC
1. Create two implemenattions of `org.flowable.engine.delegate.ExecutionListener` or `org.flowable.engine.delegate.JavaDelegate`
2. Place into on of them some expressions, like `private Expression fixedValue;`
3. Go into BPMN modeler, navigate to Executions listeners table and open Execution listener editor
4. Select as class implementation class with injected field
ER = AR
Fields table are filled with injected into class expression
5. Choose another class without any injected expressions
ER: fields table is empty
AR: fields table does not change it state
6. Choose empty value as class
ER: fields table is empty
AR: fields table does not change it state

**Comment by maistrenkoIulia** [comment]
verified
