### ISSUE TITLE
Script task with groovy script cannot be executed due to "Can't find scripting engine for 'groovy'" (port to 1.1)

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-bpm-public#79]
see https://github.com/Haulmont/jmix-bpm-public/issues/78

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.999-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3828-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
