### ISSUE TITLE
BPM generates wrong expression for 'flowable:assignee' in case of using JPQL user list provider for multi instance task

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-bpm-public#86]
See forum question https://forum.jmix.io/t/multiinstance-bpm-jpqlqueryuserlistprovider-simple-query-doesnt-work/886

In case of using JPQL user list provider it generates for user task assignee expression like 
`${bpm_JpqlQueryUserListProvider_item.username}` but it should be 
`${bpm_JpqlQueryUserListProvider_item}`

It seems that currently, we have the same problem in the case of using any user lst provider with multi instance fragment

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT3983-213
IntelliJ version: IntelliJ IDEA 2021.3 (Ultimate Edition)
