### ISSUE TITLE
BPM generates wrong expression for 'flowable:assignee' in case of using JPQL user list provider for multi instance task (port to 1.1)

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-bpm-public#88]
See https://github.com/Haulmont/jmix-bpm-public/issues/86

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.1.999-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT3983-213
IntelliJ version: IntelliJ IDEA 2021.3 (Ultimate Edition)
